; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
upload_speed = 115200
; build_unflags = -Os
lib_compat_mode = strict
lib_deps = 
	https://github.com/RobTillaart/DHT20
	https://github.com/beegee-tokyo/DHTesp
	https://github.com/adafruit/Adafruit_NeoPixel
	https://github.com/iakop/LiquidCrystal_I2C_ESP32
	bblanchon/ArduinoJson@^6.21.0
	knolleary/PubSubClient
